version: '3.4'

services:
  sql-server-scg-db:
    image: sql-server-db
    build:
      context: .
      dockerfile: assets/Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Denn#1234"
      ACCEPT_EULA: "Y"
    networks:
      - tgw-network
networks:
  tgw-network:
    driver: bridge
      